# Generated by Django 2.1.3 on 2019-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
